title: "'Influence of Operator Expertise on Robot Supervision and Intervention'"
#description: "Video Foundation Models to Enhance Intermittent Supervision"
theme: jekyll-theme-cayman
# Optional: set GitHub links in header button
github:
  is_project_page: true
  repository_url: https://github.com/yanranjiang/Influence-of-Operator-Expertise
